# Generated by Django 4.2.20 on 2025-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fahim', '0002_blog_portfolio_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
